### ISSUE TITLE
Document how to use the github version of process

### ISSUE THREAD

**Issue by capitanbatata** [haskell/process#106]
I don't know if something should be said about how to use the latest version of `process`. I've tried [the following](https://stackoverflow.com/questions/47012909/building-the-latest-version-of-process-as-a-dependency): 

```yaml
packages:
- '.'
- location:
    git: https://github.com/haskell/process.git
    commit: 2fb7e739771f4a899a12b45f8b392e4874616b89
  extra-dep: true
```

But somehow `stack` needs to run `autoreconf` before building. Maybe there is a standard way of doing this (which I don't know), but if it doesn't some information in the README would be great.
